import { Inter } from 'next/font/google';
import Sidebar from '../layouts/sidebar/sidebar';
import '../styles/globals.css';
import ReduxProvider from './reduxProvider';
import { ThemeProviders } from './themeProviders';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Material Design',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={inter.className}>
      <body>
        <ReduxProvider>
          <ThemeProviders>
            <Sidebar />
            <main className='pl-[88px]'>{children}</main>
          </ThemeProviders>
        </ReduxProvider>
      </body>
    </html>
  );
}
