import { Inter } from 'next/font/google';
import Sidebar from '../layouts/sidebar/sidebar';
import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Material Design',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={inter.className}>
      <body>
        <Sidebar />
        <main className='ml-[88px] w-screen'>{children}</main>
      </body>
    </html>
  );
}
