import { Inter } from 'next/font/google';
import { Provider, useStore } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';
import Sidebar from '../layouts/sidebar/sidebar';
import { persistor } from '../store';
import '../styles/globals.css';
import { ThemeProviders } from './themeProviders';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Material Design',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const store = useStore();
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <ThemeProviders>
              <Sidebar />
              <main className='pl-[88px]'>{children}</main>
            </ThemeProviders>
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
